# Generated by Django 5.0 on 2023-12-28 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SaleInvoice", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="Product",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="Quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="Tax",
        ),
        migrations.AddField(
            model_name="invoice",
            name="Tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="invoice",
            name="Total_Amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Quantity", models.PositiveIntegerField(default=0)),
                (
                    "Price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "Invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SaleInvoice.invoice",
                    ),
                ),
                (
                    "Product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SaleInvoice.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="Products",
            field=models.ManyToManyField(
                through="SaleInvoice.InvoiceItem", to="SaleInvoice.product"
            ),
        ),
    ]
