# Generated by Django 5.0 on 2023-12-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SaleInvoice", "0002_remove_invoice_product_remove_invoice_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="Tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="Total_Amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
